import { expect, test } from "@playwright/test";
const url = "file://" + process.cwd() + "/dist-standalone/chief-mate-prep.html";
test("standalone file: onboard, quiz, calc, oral, mock — no server", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  await page.goto(url);
  await page.getByRole("radio", { name: /Philippines/ }).click();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Your name").fill("Juan");
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("button", { name: "Download & start" }).click();
  await expect(page.getByRole("heading", { name: /Juan/ })).toBeVisible();
  await page.getByRole("link", { name: /Mixed practice/ }).click();
  await page.locator('[data-testid^="option-"][data-correct="true"]').click();
  await page.getByTestId("conf-sure").click();
  await expect(page.getByTestId("feedback")).toContainText("Correct");
  await page.goto(url + "#/calc/stab-calc-drydock");
  await expect(page.getByTestId("calc-stem")).toContainText("drydock");
  await page.goto(url + "#/oral");
  await page.getByTestId("start-oral").click();
  await expect(page.getByTestId("transcript")).toContainText("assessment");
  await page.goto(url + "#/colregs");
  await expect(page.getByText("Head-on at night")).toBeVisible();
  await page.goto(url + "#/study");
  await expect(page.getByTestId("competence-STAB")).toBeVisible();
  await page.screenshot({ path: "/tmp/claude-0/-home-user-Nautical-Prep/6581d1e5-d048-528c-8828-602e6810ab3d/scratchpad/study.png" });
  await page.goto(url);
  await page.screenshot({ path: "/tmp/claude-0/-home-user-Nautical-Prep/6581d1e5-d048-528c-8828-602e6810ab3d/scratchpad/home.png", fullPage: false });
  expect(errors).toEqual([]);
});
