/**
 * Upsert validated content into Postgres.
 * - With SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY: upserts via the REST API (service role, server-side only).
 * - Without: writes supabase/seed-content.sql (dry run) so the import can be applied with psql / `supabase db reset`.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadContent, ROOT } from "./content-lib";

const c = loadContent();
if (c.errors.length) {
  console.error("Content invalid — run pnpm content:validate");
  process.exit(1);
}
const items = c.items.map((i) => ({
  id: i.id, type: i.type, competence: i.competence, topic: i.topic, countries: i.countries, difficulty: i.difficulty,
  status: i.status, needs_review: i.needs_review, last_reviewed: i.last_reviewed, reviewer: i.reviewer, body: i,
}));
const configs = [...c.configs.values()].map((cfg) => ({ code: cfg.code, config: cfg, status: cfg.status }));
const scenarios = c.scenarios.map((s) => ({ id: s.id, body: s, status: s.status }));

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

async function upsert(table: string, rows: unknown[]) {
  for (let i = 0; i < rows.length; i += 200) {
    const res = await fetch(`${url}/rest/v1/${table}`, {
      method: "POST",
      headers: { apikey: key!, authorization: `Bearer ${key}`, "content-type": "application/json", prefer: "resolution=merge-duplicates" },
      body: JSON.stringify(rows.slice(i, i + 200)),
    });
    if (!res.ok) throw new Error(`${table}: ${res.status} ${await res.text()}`);
  }
}

const q = (v: unknown) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a: string[]) => `'{${a.map((x) => `"${x}"`).join(",")}}'`;

if (url && key) {
  await upsert("country_configs", configs);
  await upsert("items", items);
  await upsert("colreg_scenarios", scenarios);
  console.log(`✓ Imported ${items.length} items, ${configs.length} configs, ${scenarios.length} scenarios into ${url}`);
} else {
  const sql = [
    "-- Generated by scripts/import-content.ts — do not edit by hand.",
    "begin;",
    ...configs.map((r) => `insert into public.country_configs (code, config, status) values (${q(r.code)}, ${q(JSON.stringify(r.config))}::jsonb, ${q(r.status)}) on conflict (code) do update set config = excluded.config, status = excluded.status, updated_at = now();`),
    ...items.map((r) => `insert into public.items (id, type, competence, topic, countries, difficulty, status, needs_review, last_reviewed, reviewer, body) values (${q(r.id)}, ${q(r.type)}, ${q(r.competence)}, ${q(r.topic)}, ${arr(r.countries)}, ${r.difficulty}, ${q(r.status)}, ${r.needs_review}, ${q(r.last_reviewed)}, ${q(r.reviewer)}, ${q(JSON.stringify(r.body))}::jsonb) on conflict (id) do update set type = excluded.type, competence = excluded.competence, topic = excluded.topic, countries = excluded.countries, difficulty = excluded.difficulty, status = excluded.status, needs_review = excluded.needs_review, last_reviewed = excluded.last_reviewed, reviewer = excluded.reviewer, body = excluded.body, updated_at = now();`),
    ...scenarios.map((r) => `insert into public.colreg_scenarios (id, body, status) values (${q(r.id)}, ${q(JSON.stringify(r.body))}::jsonb, ${q(r.status)}) on conflict (id) do update set body = excluded.body, status = excluded.status, updated_at = now();`),
    "commit;",
  ].join("\n");
  const out = join(ROOT, "supabase/seed-content.sql");
  writeFileSync(out, sql);
  console.log(`✓ Dry run (no SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY): wrote ${items.length} items, ${configs.length} configs, ${scenarios.length} scenarios to supabase/seed-content.sql`);
}
